package = "lux-lua"
lua = ">=5.1,< 5.6"

[description]
summary = "The Lua API for the lux package manager"
maintainer = "Lumen Labs"
homepage = "https://lux.lumen-labs.org"
issues_url = "https://github.com/lumen-oss/lux/issues"
labels = ["luarocks", "lux", "package-manager", "packagemanager", "build"]
license = "LGPL-3.0+"

[source]
url = "https://github.com/lumen-oss/lux/archive/refs/tags/$(REF).zip"
dev = "git+https://github.com/lumen-oss/lux.git"

[build]
type = "rust-mlua"
cargo_extra_args = ["--package", "lux-lua", "--locked"]
features = ["vendored"]

[build.modules]
lux = "lux_lua"
